### ISSUE TITLE
User should be able to Combine or seperate graphs by leaflet or by tail in nougat.py

### ISSUE THREAD

**Issue by JahmalEnnis** [BranniganLab/nougat#65] opened 2023-01-21 16:20 UTC
Ability to graph information between leaflets and chains together on same plot

**Comment by JesseSandberg** [comment] 2023-01-22 16:42
This is potentially a duplicate of #27

**Comment by JesseSandberg** [comment] 2023-01-22 18:17
also @JahmalEnnis nougat already separates things by leaflet. Can you tell me a use case for combining leaflets together?

**Comment by JesseSandberg** [comment] 2023-03-03 16:50
closing as duplicate of issue #27

**Closed by JesseSandberg** 2023-03-03 16:50 UTC
Labels: enhancement
